name: 'Custom JavaScript Action'
description: 'A boilerplate custom JavaScript action using Node 20'
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: false
    default: 'World'
outputs:
  time:
    description: 'The time we greeted you'
runs:
  using: 'node20'
  pre: 'dist/pre/index.js'
  main: 'dist/index.js'
  post: 'dist/post/index.js'
