import logging
import sys
import datetime
import os
from agents.researcher import ResearcherAgent
from agents.analyzer import AnalyzerAgent
from agents.intelligence import IntelligenceAgent
from agents.content_creator import ContentCreatorAgent
from agents.health_check import HealthCheckAgent
from agents.monetization import MonetizationAgent
from agents.creativity import CreativityAgent
from agents.advertising import AdvertisingAgent

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger("Orchestrator")

def run_orchestration(save_report=True):
    logger.info(">>> STARTING AUTONOMOUS AGENT SWARM (v2.0 - Evolving) <<<")
    report_data = {}

    # 1. Health Check
    health_agent = HealthCheckAgent()
    health_status = health_agent.run()
    report_data['health'] = health_status

    if health_status.get("site_status") != "healthy":
        logger.error("Target site is unhealthy. Aborting operation.")

    # 2. Research
    research_agent = ResearcherAgent()
    raw_data = research_agent.run({"limit": 2})
    report_data['research'] = {
        'posts_scraped': len(raw_data.get('blog_posts', [])),
        'google_results': len(raw_data.get('google_listings', []))
    }

    if not raw_data.get('blog_posts'):
        logger.warning("No blog data scraped.")

    # 3. Analyze
    analyzer_agent = AnalyzerAgent()
    analysis_result = analyzer_agent.run(raw_data)
    report_data['analysis'] = analysis_result

    # 3.5 Advertising (Collaborating with Analyzer)
    ad_agent = AdvertisingAgent()
    ad_result = ad_agent.run(analysis_result)
    report_data['advertising'] = ad_result

    # 4. Intelligence (Collaborating with Analyzer + Advertising + History)
    intelligence_agent = IntelligenceAgent()
    # Pass combined data for "100% collaboration"
    combined_input = {
        "analysis": analysis_result,
        "advertising": ad_result
    }
    intelligence_result = intelligence_agent.run(combined_input)
    report_data['intelligence'] = intelligence_result

    # 5. Creativity
    creativity_agent = CreativityAgent()
    creative_result = creativity_agent.run(analysis_result)
    report_data['creativity'] = creative_result

    # 6. Monetization
    monetization_agent = MonetizationAgent()
    monetization_result = monetization_agent.run(raw_data.get('blog_posts', []))
    report_data['monetization'] = monetization_result

    # 7. Create Content
    content_agent = ContentCreatorAgent()
    content_draft = content_agent.run(intelligence_result)
    report_data['content_draft'] = content_draft

    logger.info(">>> SWARM OPERATION COMPLETE <<<")

    if save_report:
        save_daily_report(report_data)

    return report_data

def save_daily_report(data):
    today = datetime.datetime.now().strftime("%Y-%m-%d")
    report_dir = "reports"
    os.makedirs(report_dir, exist_ok=True)
    report_file = os.path.join(report_dir, f"daily_report_{today}.md")

    with open(report_file, "w", encoding="utf-8") as f:
        f.write(f"# 📊 Daily Autonomous Report: {today}\n")
        f.write("*(Generated by Jules Autonomous Swarm with Continuous Learning)*\n\n")

        # Executive Summary
        f.write("## 📋 Executive Summary\n")
        f.write("| Metric | Value | Status |\n")
        f.write("| :--- | :--- | :--- |\n")

        # Health Status Logic
        health = data.get('health', {})
        site_status = health.get('site_status')
        status_icon = "✅" if site_status == "healthy" else "❌"
        f.write(f"| **System Health** | {site_status} | {status_icon} |\n")

        # Research Stats Logic
        research = data.get('research', {})
        posts = research.get('posts_scraped', 0)
        posts_icon = "📈" if posts > 0 else "⚠️"
        f.write(f"| **New Content Scraped** | {posts} posts | {posts_icon} |\n")

        # Evolution Status Logic
        intel = data.get('intelligence', {})
        evo_status = intel.get('evolution_status', 'Unknown')
        f.write(f"| **Evolution Status** | {evo_status} | 🧬 |\n\n")

        # Health
        f.write("## 🏥 1. System Health & Environment\n")
        f.write(f"- **Site Status:** {site_status} (Code: {health.get('site_code')})\n")
        robots_access = '✅ Allowed' if health.get('robots_txt_accessible') else '❌ Blocked'
        googlebot_allowed = '✅ Yes' if health.get('googlebot_allowed') else '❌ No'
        f.write(f"- **Robots.txt Access:** {robots_access}\n")
        f.write(f"- **Googlebot Allowed:** {googlebot_allowed}\n\n")

        # Research Stats
        f.write("## 🔎 2. Research Summary\n")
        f.write(f"- **New Posts Scraped:** {posts}\n")
        f.write(f"- **Google Listings Found:** {research.get('google_results')}\n\n")

        # Intelligence & Evolution
        f.write("## 🧠 3. Strategic Intelligence & Evolution\n")
        f.write(f"- **Evolution Status:** {evo_status}\n")
        f.write(f"- **Recommended Focus:** {intel.get('recommended_focus')}\n")

        insights = intel.get('insights', [])
        if insights:
            f.write("### Key Insights\n")
            for insight in insights:
                f.write(f"- 💡 {insight}\n")
        f.write("\n")

        # Advertising
        ads = data.get('advertising', {})
        f.write("## 🎯 4. Advertising & Targeting\n")
        f.write(f"- **Target Audience:** {ads.get('target_audience')}\n")
        f.write("- **Bid Strategy:**\n")
        for bid in ads.get('bid_strategy', []):
            f.write(f"  - **{bid['keyword']}**: ${bid['suggested_bid']} ({bid['strategy']})\n")
        f.write("\n")

        # Monetization
        money = data.get('monetization', {})
        f.write("## 💰 5. Monetization Review\n")
        f.write(f"- **Summary:** {money.get('summary')}\n")
        for detail in money.get('details', []):
            f.write(f"- {detail}\n")
        f.write("\n")

        # Creativity
        creative = data.get('creativity', {})
        ideas = creative.get('creative_ideas', [])
        f.write("## 🎨 6. Creative Brainstorming\n")

        if len(ideas) > 5:
            f.write(f"<details>\n<summary>View {len(ideas)} Creative Ideas</summary>\n\n")
            for idea in ideas:
                f.write(f"- {idea}\n")
            f.write("\n</details>\n")
        else:
            for idea in ideas:
                f.write(f"- {idea}\n")
        f.write("\n")

        # Content Draft
        draft = data.get('content_draft', {})
        f.write("## 📝 7. Automated Content Draft\n")
        f.write(f"### {draft.get('draft_title', 'Untitled')}\n\n")
        f.write(draft.get('draft_content', ''))

    logger.info("Report saved to %s", report_file)

if __name__ == "__main__":
    run_orchestration()
