import logging
import sys
import datetime
import os
from agents.researcher import ResearcherAgent
from agents.analyzer import AnalyzerAgent
from agents.intelligence import IntelligenceAgent
from agents.content_creator import ContentCreatorAgent
from agents.health_check import HealthCheckAgent
from agents.monetization import MonetizationAgent
from agents.creativity import CreativityAgent
from agents.advertising import AdvertisingAgent

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger("Orchestrator")

def run_orchestration(save_report=True):
    logger.info(">>> STARTING AUTONOMOUS AGENT SWARM (v2.0 - Evolving) <<<")
    report_data = {}

    # 1. Health Check
    health_agent = HealthCheckAgent()
    health_status = health_agent.run()
    report_data['health'] = health_status

    if health_status.get("site_status") != "healthy":
        logger.error("Target site is unhealthy. Aborting operation.")

    # 2. Research
    research_agent = ResearcherAgent()
    raw_data = research_agent.run({"limit": 2})
    report_data['research'] = {
        'posts_scraped': len(raw_data.get('blog_posts', [])),
        'google_results': len(raw_data.get('google_listings', []))
    }

    if not raw_data.get('blog_posts'):
        logger.warning("No blog data scraped.")

    # 3. Analyze
    analyzer_agent = AnalyzerAgent()
    analysis_result = analyzer_agent.run(raw_data)
    report_data['analysis'] = analysis_result

    # 3.5 Advertising (Collaborating with Analyzer)
    ad_agent = AdvertisingAgent()
    ad_result = ad_agent.run(analysis_result)
    report_data['advertising'] = ad_result

    # 4. Intelligence (Collaborating with Analyzer + Advertising + History)
    intelligence_agent = IntelligenceAgent()
    # Pass combined data for "100% collaboration"
    combined_input = {
        "analysis": analysis_result,
        "advertising": ad_result
    }
    intelligence_result = intelligence_agent.run(combined_input)
    report_data['intelligence'] = intelligence_result

    # 5. Creativity
    creativity_agent = CreativityAgent()
    creative_result = creativity_agent.run(analysis_result)
    report_data['creativity'] = creative_result

    # 6. Monetization
    monetization_agent = MonetizationAgent()
    monetization_result = monetization_agent.run(raw_data.get('blog_posts', []))
    report_data['monetization'] = monetization_result

    # 7. Create Content
    content_agent = ContentCreatorAgent()
    content_draft = content_agent.run(intelligence_result)
    report_data['content_draft'] = content_draft

    logger.info(">>> SWARM OPERATION COMPLETE <<<")

    if save_report:
        save_daily_report(report_data)

    return report_data

def save_daily_report(data):
    today = datetime.datetime.now().strftime("%Y-%m-%d")
    report_dir = "reports"
    os.makedirs(report_dir, exist_ok=True)
    report_file = os.path.join(report_dir, f"daily_report_{today}.md")

    # Extract Key Metrics for Summary
    status = data.get('health', {})
    research = data.get('research', {})
    intel = data.get('intelligence', {})
    ads = data.get('advertising', {})
    draft = data.get('content_draft', {})

    site_status = status.get('site_status', 'unknown')
    health_emoji = "✅" if site_status == "healthy" else "❌"

    posts_count = research.get('posts_scraped', 0)
    focus_topic = intel.get('recommended_focus', 'General')

    with open(report_file, "w", encoding="utf-8") as f:
        f.write(f"# 🎨 Daily Autonomous Report: {today}\n")
        f.write("*(Generated by Jules Autonomous Swarm with Continuous Learning)*\n\n")

        # --- EXECUTIVE SUMMARY ---
        f.write("## 📊 Executive Summary\n\n")
        f.write("| Metric | Status | Details |\n")
        f.write("| :--- | :---: | :--- |\n")
        f.write(f"| **System Health** | {health_emoji} | {site_status.title()} (Code: {status.get('site_code')}) |\n")
        f.write(f"| **Research** | 🔎 | {posts_count} posts scraped, {research.get('google_results', 0)} Google results |\n")
        f.write(f"| **Strategic Focus** | 🎯 | {focus_topic} |\n")
        f.write(f"| **Target Audience** | 👥 | {ads.get('target_audience', 'General')} |\n\n")

        # --- DETAILED SECTIONS ---

        # 1. Health
        f.write("## 1. System Health & Environment\n")
        f.write(f"- **Site Status:** {health_emoji} {site_status} (Code: {status.get('site_code')})\n")
        f.write(f"- **Robots.txt Access:** {'✅' if status.get('robots_txt_accessible') else '❌'}\n")
        f.write(f"- **Googlebot Allowed:** {'✅' if status.get('googlebot_allowed') else '❌'}\n\n")

        # 2. Research & Intelligence (Collapsible)
        f.write("## 2. Research & Intelligence\n")
        f.write(f"**Evolution Status:** {intel.get('evolution_status')}\n\n")

        f.write("<details>\n<summary><strong>🧠 View Strategic Insights</strong></summary>\n\n")
        for insight in intel.get('insights', []):
            f.write(f"- 💡 {insight}\n")
        f.write("</details>\n\n")

        # 3. Advertising Strategy (Collapsible)
        f.write("## 3. Advertising Strategy\n")
        f.write(f"**Target Audience:** {ads.get('target_audience')}\n\n")

        f.write("<details>\n<summary><strong>💰 View Bid Strategy</strong></summary>\n\n")
        f.write("| Keyword | Bid | Strategy |\n")
        f.write("| :--- | :--- | :--- |\n")
        for bid in ads.get('bid_strategy', []):
            f.write(f"| {bid['keyword']} | {bid['suggested_bid']} | {bid['strategy']} |\n")
        f.write("\n</details>\n\n")

        # 4. Monetization & Creativity (Collapsible)
        money = data.get('monetization', {})
        creative = data.get('creativity', {})

        f.write("## 4. Monetization & Ideas\n")
        f.write(f"**Monetization Summary:** {money.get('summary')}\n\n")

        f.write("<details>\n<summary><strong>💸 Monetization Details</strong></summary>\n\n")
        for detail in money.get('details', []):
            f.write(f"- {detail}\n")
        f.write("</details>\n\n")

        f.write("<details>\n<summary><strong>✨ Creative Brainstorming</strong></summary>\n\n")
        for idea in creative.get('creative_ideas', []):
            f.write(f"- 🎨 {idea}\n")
        f.write("</details>\n\n")

        # 5. Content Draft (Collapsible)
        f.write("## 5. Automated Content Draft\n")
        f.write(f"### 📝 {draft.get('draft_title', 'Untitled')}\n\n")

        f.write("<details open>\n<summary><strong>📖 Read Full Draft</strong></summary>\n\n")
        f.write(draft.get('draft_content', ''))
        f.write("\n</details>\n")

    logger.info(f"Report saved to {report_file}")

if __name__ == "__main__":
    run_orchestration()
