import logging
import sys
import datetime
import os
from agents.researcher import ResearcherAgent
from agents.analyzer import AnalyzerAgent
from agents.intelligence import IntelligenceAgent
from agents.content_creator import ContentCreatorAgent
from agents.health_check import HealthCheckAgent
from agents.monetization import MonetizationAgent
from agents.creativity import CreativityAgent
from agents.advertising import AdvertisingAgent

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger("Orchestrator")

def run_orchestration(save_report=True):
    logger.info(">>> STARTING AUTONOMOUS AGENT SWARM (v2.0 - Evolving) <<<")
    report_data = {}

    # 1. Health Check
    health_agent = HealthCheckAgent()
    health_status = health_agent.run()
    report_data['health'] = health_status

    if health_status.get("site_status") != "healthy":
        logger.error("Target site is unhealthy. Aborting operation.")

    # 2. Research
    research_agent = ResearcherAgent()
    raw_data = research_agent.run({"limit": 2})
    report_data['research'] = {
        'posts_scraped': len(raw_data.get('blog_posts', [])),
        'google_results': len(raw_data.get('google_listings', []))
    }

    if not raw_data.get('blog_posts'):
        logger.warning("No blog data scraped.")

    # 3. Analyze
    analyzer_agent = AnalyzerAgent()
    analysis_result = analyzer_agent.run(raw_data)
    report_data['analysis'] = analysis_result

    # 3.5 Advertising (Collaborating with Analyzer)
    ad_agent = AdvertisingAgent()
    ad_result = ad_agent.run(analysis_result)
    report_data['advertising'] = ad_result

    # 4. Intelligence (Collaborating with Analyzer + Advertising + History)
    intelligence_agent = IntelligenceAgent()
    # Pass combined data for "100% collaboration"
    combined_input = {
        "analysis": analysis_result,
        "advertising": ad_result
    }
    intelligence_result = intelligence_agent.run(combined_input)
    report_data['intelligence'] = intelligence_result

    # 5. Creativity
    creativity_agent = CreativityAgent()
    creative_result = creativity_agent.run(analysis_result)
    report_data['creativity'] = creative_result

    # 6. Monetization
    monetization_agent = MonetizationAgent()
    monetization_result = monetization_agent.run(raw_data.get('blog_posts', []))
    report_data['monetization'] = monetization_result

    # 7. Create Content
    content_agent = ContentCreatorAgent()
    content_draft = content_agent.run(intelligence_result)
    report_data['content_draft'] = content_draft

    logger.info(">>> SWARM OPERATION COMPLETE <<<")

    if save_report:
        save_daily_report(report_data)

    return report_data

def generate_report_markdown(data, date_str):
    content = []
    # Add top anchor
    content.append(f"<a name=\"top\"></a>\n")
    content.append(f"# Daily Autonomous Report: {date_str}\n")
    content.append("*(Generated by Jules Autonomous Swarm with Continuous Learning)*\n\n")

    # Table of Contents
    content.append("## 📋 Table of Contents\n")
    content.append("- [🏥 System Health & Environment](#health)\n")
    content.append("- [🔍 Research Summary](#research)\n")
    content.append("- [🧠 Strategic Intelligence & Evolution](#intelligence)\n")
    content.append("- [📢 Advertising & Targeting](#advertising)\n")
    content.append("- [💰 Monetization Review](#monetization)\n")
    content.append("- [🎨 Creative Brainstorming](#creativity)\n")
    content.append("- [📝 Automated Content Draft](#content)\n\n")
    content.append("---\n\n")

    # Health
    content.append("<a name=\"health\"></a>\n")
    content.append("## 🏥 1. System Health & Environment\n")
    status = data.get('health', {})
    content.append(f"- **Site Status:** {status.get('site_status')} (Code: {status.get('site_code')})\n")
    content.append(f"- **Robots.txt Access:** {status.get('robots_txt_accessible')}\n")
    content.append(f"- **Googlebot Allowed:** {status.get('googlebot_allowed')}\n")
    content.append("[⬆️ Back to Top](#top)\n\n")

    # Research Stats
    research = data.get('research', {})
    content.append("<a name=\"research\"></a>\n")
    content.append("## 🔍 2. Research Summary\n")
    content.append(f"- **New Posts Scraped:** {research.get('posts_scraped')}\n")
    content.append(f"- **Google Listings Found:** {research.get('google_results')}\n")
    content.append("[⬆️ Back to Top](#top)\n\n")

    # Intelligence & Evolution
    intel = data.get('intelligence', {})
    content.append("<a name=\"intelligence\"></a>\n")
    content.append("## 🧠 3. Strategic Intelligence & Evolution\n")
    content.append(f"- **Evolution Status:** {intel.get('evolution_status')}\n")
    content.append(f"- **Recommended Focus:** {intel.get('recommended_focus')}\n")
    for insight in intel.get('insights', []):
        content.append(f"- {insight}\n")
    content.append("\n[⬆️ Back to Top](#top)\n\n")

    # Advertising
    ads = data.get('advertising', {})
    content.append("<a name=\"advertising\"></a>\n")
    content.append("## 📢 4. Advertising & Targeting (Google Antigravity Colab)\n")
    content.append(f"- **Target Audience:** {ads.get('target_audience')}\n")
    content.append("- **Bid Strategy:**\n")
    for bid in ads.get('bid_strategy', []):
        content.append(f"  - **{bid['keyword']}**: {bid['suggested_bid']} ({bid['strategy']})\n")
    content.append("\n[⬆️ Back to Top](#top)\n\n")

    # Monetization
    money = data.get('monetization', {})
    content.append("<a name=\"monetization\"></a>\n")
    content.append("## 💰 5. Monetization Review\n")
    content.append(f"- **Summary:** {money.get('summary')}\n")
    for detail in money.get('details', []):
        content.append(f"- {detail}\n")
    content.append("\n[⬆️ Back to Top](#top)\n\n")

    # Creativity
    creative = data.get('creativity', {})
    content.append("<a name=\"creativity\"></a>\n")
    content.append("## 🎨 6. Creative Brainstorming\n")
    for idea in creative.get('creative_ideas', []):
        content.append(f"- {idea}\n")
    content.append("\n[⬆️ Back to Top](#top)\n\n")

    # Content Draft
    draft = data.get('content_draft', {})
    content.append("<a name=\"content\"></a>\n")
    content.append("## 📝 7. Automated Content Draft\n")
    content.append(f"### {draft.get('draft_title', 'Untitled')}\n\n")
    content.append(draft.get('draft_content', ''))
    content.append("\n\n[⬆️ Back to Top](#top)\n")

    return "".join(content)

def save_daily_report(data):
    today = datetime.datetime.now().strftime("%Y-%m-%d")
    report_dir = "reports"
    os.makedirs(report_dir, exist_ok=True)
    report_file = os.path.join(report_dir, f"daily_report_{today}.md")

    report_content = generate_report_markdown(data, today)

    with open(report_file, "w", encoding="utf-8") as f:
        f.write(report_content)

    logger.info(f"Report saved to {report_file}")

if __name__ == "__main__":
    run_orchestration()
