name = "8bukets"
main = "index.js"
compatibility_date = "2024-04-03"
compatibility_flags = [ "nodejs_compat" ]

# Disable routes for CI build stability
# routes = [
#   { pattern = "edge.example.com", custom_domain = true }
# ]

[[kv_namespaces]]
binding = "PRESENCE_KV"
id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
