/**
 * GITKRAKEN METADATA SERVICE
 * Optimizes commit messages and branches for visual clarity in GitKraken.
 */

export interface CommitMetadata {
  type: 'feat' | 'fix' | 'chore' | 'docs' | 'refactor' | 'agent'
  scope?: string
  subject: string
  body?: string
  roadmap?: string
  progress?: number // 0-100
}

export class GitKrakenMetadataService {
  /**
   * Formats a commit message following Conventional Commits with visual hints.
   */
  public formatCommitMessage(metadata: CommitMetadata): string {
    const scopeStr = metadata.scope ? `(${metadata.scope})` : ''
    let message = `${metadata.type}${scopeStr}: ${metadata.subject}\n\n`

    if (metadata.body) {
      message += `${metadata.body}\n\n`
    }

    // GitKraken friendly markers
    if (metadata.roadmap) {
      message += `Roadmap: ${metadata.roadmap}\n`
    }

    if (metadata.progress !== undefined) {
      message += `Progress: [${'#'.repeat(Math.floor(metadata.progress / 10))}${' '.repeat(10 - Math.floor(metadata.progress / 10))}] ${metadata.progress}%\n`
    }

    message += `\n🤖 Generated by Antigravity Autonomous Engine`
    return message
  }

  /**
   * Optimizes branch names for GitKraken folder grouping.
   */
  public formatBranchName(type: string, feature: string): string {
    const sanitizedFeature = feature.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '')
    return `${type}/${sanitizedFeature}`
  }
}

export const gitKrakenMetadataService = new GitKrakenMetadataService()
