import { describe, it, expect } from 'vitest'
import { gitKrakenMetadataService } from './gitkraken'

describe('GitKrakenMetadataService', () => {
  it('should format commit message with progress bar', () => {
    const msg = gitKrakenMetadataService.formatCommitMessage({
      type: 'feat',
      subject: 'add cloud sync',
      progress: 50
    })
    expect(msg).toContain('feat: add cloud sync')
    expect(msg).toContain('Progress: [#####     ] 50%')
    expect(msg).toContain('🤖 Generated by Antigravity Autonomous Engine')
  })

  it('should format branch names with folders', () => {
    const branch = gitKrakenMetadataService.formatBranchName('feat', 'Cloud Sync Service')
    expect(branch).toBe('feat/cloud-sync-service')
  })
})
