from .base_agent import BaseAgent
from typing import Dict
import os
import time

GENERATED_CODE_DIR = "generated_code"

class CodeGeneratorAgent(BaseAgent):
    def __init__(self):
        super().__init__("Code Generator Agent")

    def process(self, dna: Dict, intelligence: Dict) -> str:
        self.log("Generating physical code based on intelligence...")

        os.makedirs(GENERATED_CODE_DIR, exist_ok=True)

        iq = dna.get("system_iq", 25)
        strategy = intelligence.get("strategic_insight", "Neutral")

        # Generate a python script based on "ideas"
        filename = f"strategy_v{dna.get('evolution_generation', 0)}.py"
        filepath = os.path.join(GENERATED_CODE_DIR, filename)

        code_content = f"""# Generated by CodeGeneratorAgent
# System IQ: {iq}
# Strategy: {strategy}
# Date: {time.strftime('%Y-%m-%d')}

def execute_strategy():
    print("Executing automated strategy: {strategy}")
    target_iq = {iq}
    if target_iq > 50:
        print("Advanced Mode Active")
    else:
        print("Standard Mode Active")

if __name__ == "__main__":
    execute_strategy()
"""

        with open(filepath, 'w') as f:
            f.write(code_content)

        return f"Generated {filepath}"
