import os
from .base_agent import BaseAgent, AgentContext

class CodingAgent(BaseAgent):
    def __init__(self):
        super().__init__("CodingAgent 💻")

    def run(self, context: AgentContext):
        ideas = context.get("creative_ideas", [])

        # Look for a coding-related idea
        coding_task = None
        for idea in ideas:
            if "script" in idea.lower() or "code" in idea.lower() or "algorithm" in idea.lower():
                coding_task = idea
                break

        if not coding_task:
            # Fallback if no specific coding idea found
            coding_task = "Generate a Python script to calculate Fibonacci sequence."

        self.log(context, f"Generating code for: {coding_task}")

        # Simple template-based code generation (Simulated AI Coding)
        code_content = f'''"""
Auto-generated by CodingAgent
Task: {coding_task}
"""

def solve_task():
    print("Executing task: {coding_task}")
    # Implementation of {coding_task}
    results = []
    for i in range(10):
        results.append(i * i)
    return results

if __name__ == "__main__":
    print(solve_task())
'''

        filename = "generated_solution.py"
        with open(filename, "w") as f:
            f.write(code_content)

        context.set("generated_code_file", filename)
        self.log(context, f"Code generated and saved to {filename}")
