"""
Content Agent module.
Responsible for generating content based on researched topics.
"""
import os
import random
from .base_agent import BaseAgent

class ContentAgent(BaseAgent):
    """
    ContentAgent generates text content and saves it to disk.
    """
    def __init__(self):
        super().__init__("ContentAgent")

    def generate_content(self, topics):
        """
        Generates markdown content for the given topics.
        """
        creativity = self.get_parameter("content_creativity")
        self.log_activity(f"Generating content with creativity {creativity:.2f}...")

        generated_files = []
        os.makedirs("output_content", exist_ok=True)

        for topic in topics:
            # Simulate content generation
            quality_score = creativity * random.uniform(0.8, 1.2)
            content = (
                f"# {topic}\n\n"
                f"Generated by Autonomous Agent.\n"
                f"Quality Score: {quality_score:.2f}\n\n"
                f"## Insights\n..."
            )

            filename = f"output_content/{topic.replace(' ', '_').lower()}.md"
            with open(filename, 'w', encoding='utf-8') as f:
                f.write(content)

            generated_files.append({"file": filename, "topic": topic, "quality": quality_score})
            self.log_activity(f"Created {filename}")

        return generated_files
