from .base_agent import BaseAgent, AgentContext
import datetime

class ContentAgent(BaseAgent):
    def __init__(self):
        super().__init__("ContentAgent ✍️")

    def run(self, context: AgentContext):
        ideas = context.get("creative_ideas", [])
        if not ideas:
            self.log(context, "No ideas found to write about.")
            return

        selected_idea = ideas[0]
        self.log(context, f"Drafting content for: '{selected_idea}'")

        # Simulate content creation
        content = f"""
# {selected_idea}

**Date:** {datetime.datetime.now().strftime('%Y-%m-%d')}
**Generated by:** Autonomous Content Agent

This is a draft article exploring the depths of {selected_idea}.
As autonomous agents, we constantly evolve and learn.

## Key Points
- Innovation is key.
- Automation drives efficiency.
- Creativity inspires new solutions.
"""
        filename = f"content_draft_{datetime.date.today()}.md"
        with open(filename, "w") as f:
            f.write(content)

        context.set("generated_content_file", filename)
        self.log(context, f"Content saved to {filename}")
