from datetime import datetime
from .base_agent import BaseAgent

class ContentAgent(BaseAgent):
    def __init__(self):
        super().__init__("Content Agent")

    def run(self, data: dict) -> dict:
        """
        Generates a content draft based on Intelligence.
        """
        brief = data.get('intelligence', {}).get('brief', "No brief available.")
        insight = data.get('intelligence', {}).get('actionable_insight', "")

        draft = f"""
# Content Draft: {datetime.now().strftime('%Y-%m-%d')}

## Executive Summary
{brief}

## Core Message
{insight}

## Proposed Article Outline
1. Introduction: defining the current landscape.
2. The impact of recent trends.
3. Case studies/Examples.
4. Future outlook.
5. Conclusion.

*Generated by Autonomous Content Agent*
"""
        return {
            "draft": draft
        }
