import json
import os
import logging
from typing import List, Dict, Any
from .base_agent import BaseAgent, Blackboard

class KnowledgeMergeAgent(BaseAgent):
    """
    Agent that consolidates AI knowledge, market intelligence, and technical documentation.
    Produces a unified intelligence store.
    """
    def __init__(self):
        super().__init__("KnowledgeMergeAgent",
                         dependencies=["analysis_stats", "ai_agents_definitions"],
                         provides=["consolidated_knowledge"])
        self.output_json = "data/consolidated_knowledge.json"
        self.output_md = "CONSOLIDATED_KNOWLEDGE.md"

    async def run(self, data: list, blackboard: Blackboard) -> dict:
        self.logger.info("Consolidating all system knowledge...")

        # 1. Gather data from blackboard
        analysis_stats = blackboard.get("analysis_stats", {})
        ai_definitions = blackboard.get("ai_agents_definitions", {})

        # 2. Gather data from technical JSON files
        technical_docs = self._load_technical_docs()

        # 3. Construct consolidated object
        consolidated = {
            "metadata": {
                "timestamp": self._get_timestamp(),
                "agent_version": self.config.get("current_version", 1.0)
            },
            "ai_agents": ai_definitions,
            "market_intelligence": {
                "total_posts": analysis_stats.get("total_posts"),
                "top_domains": analysis_stats.get("top_domains"),
                "top_categories": analysis_stats.get("top_categories")
            },
            "technical_documentation": technical_docs
        }

        # 4. Save to files
        self._save_json(consolidated)
        self._save_markdown(consolidated)

        self.logger.info(f"Consolidated knowledge saved to {self.output_json} and {self.output_md}")

        return {"consolidated_knowledge": consolidated}

    def _load_technical_docs(self) -> Dict[str, Any]:
        docs = {}
        files = {
            "gemma": "gemmafour_docs.json",
            "litert": "litert_docs.json",
            "stitch": "stitch_docs.json",
            "intelephense": "intelephense_docs.json",
            "vscode_intelephense": "vscode_intelephense_docs.json"
        }

        for key, filename in files.items():
            if os.path.exists(filename):
                try:
                    with open(filename, "r", encoding="utf-8") as f:
                        docs[key] = json.load(f)
                except Exception as e:
                    self.logger.error(f"Failed to load {filename}: {e}")
            else:
                self.logger.warning(f"Technical doc file {filename} not found.")

        return docs

    def _save_json(self, data: Dict[str, Any]):
        try:
            os.makedirs(os.path.dirname(self.output_json), exist_ok=True)
            with open(self.output_json, "w", encoding="utf-8") as f:
                json.dump(data, f, indent=4, ensure_ascii=False)
        except Exception as e:
            self.logger.error(f"Failed to save JSON: {e}")

    def _save_markdown(self, data: Dict[str, Any]):
        try:
            with open(self.output_md, "w", encoding="utf-8") as f:
                f.write("# 🧠 Consolidated Knowledge Base\n\n")
                f.write(f"**Last Updated:** {data['metadata']['timestamp']}\n")
                f.write(f"**System Version:** v{data['metadata']['agent_version']}\n\n")

                f.write("## 1. AI Agent Definitions & Best Practices\n")
                ai = data.get("ai_agents", {})
                f.write(f"**Core Definition:** {ai.get('ai_agent', 'N/A')[:200]}...\n\n")

                f.write("## 2. Market Intelligence Summary\n")
                market = data.get("market_intelligence", {})
                f.write(f"- **Total Market Signals Analyzed:** {market.get('total_posts', 0)}\n")
                f.write("- **Top Referenced Domains:** " + ", ".join(list(market.get('top_domains', {}).keys())[:5]) + "\n\n")

                f.write("## 3. Technical Documentation Index\n")
                tech = data.get("technical_documentation", {})
                for doc_name in tech.keys():
                    f.write(f"- {doc_name.replace('_', ' ').title()}\n")

                f.write("\n---\n*This report was automatically generated by the KnowledgeMergeAgent.*")
        except Exception as e:
            self.logger.error(f"Failed to save Markdown: {e}")

    def _get_timestamp(self) -> str:
        from datetime import datetime
        return datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    async def review(self, blackboard: Blackboard) -> List[str]:
        if not blackboard.get("consolidated_knowledge"):
            return ["Consolidated knowledge was not successfully produced."]
        return ["Consolidated knowledge base verified and persisted."]
