name: Auto Merge

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: write
  pull-requests: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Merge PR
        run: gh pr merge --auto --merge "$PR_URL" || true
        env:
          MACBOOK_CLOUD_SIMULATION: true
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
