name: HCP Packer Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'hcp-packer-tutorial/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest"

      - name: Packer Init
        run: packer init .
        working-directory: hcp-packer-tutorial

      - name: Packer Format Check
        run: packer fmt -check .
        working-directory: hcp-packer-tutorial

      - name: Packer Build
        env:
          HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
          HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}
          HCP_PROJECT_ID: ${{ secrets.HCP_PROJECT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: packer build ubuntu-focal.pkr.hcl
        working-directory: hcp-packer-tutorial
